DROP TABLE IF EXISTS Uses;
DROP TABLE IF EXISTS Rents;
DROP TABLE IF EXISTS Owns;

DROP TABLE IF EXISTS Listings;
DROP TABLE IF EXISTS Attractions;
DROP TABLE IF EXISTS Transportation;

DROP TABLE IF EXISTS Hosts;
DROP TABLE IF EXISTS Users;


-- DROP TABLE IF EXISTS Visits;
